"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import urllib.parse
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Dominios autorizados a enviar formularios (POST) al portal. Sin esto,
# Django rechaza con 403 cualquier POST que llegue por HTTPS desde un dominio
# distinto al que Django cree que es "el suyo" (chequeo de Origin/Referer) -
# y el checkout de la Clase 5 es exactamente un POST. En local sobre HTTP no
# hace falta, pero en Vercel (HTTPS) es obligatorio declarar el dominio.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# El portal corre detras del proxy de Vercel: la conexion real
# proxy->contenedor es HTTP, pero el navegador->proxy es HTTPS. Sin esto,
# Django cree que toda peticion es insegura y puede entrar en bucles de
# redireccion al forzar HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Las cookies de sesion y CSRF solo se marcan "Secure" cuando DEBUG esta
# apagado: en desarrollo local (HTTP) marcarlas Secure haria que el navegador
# las descartara sin avisar, dejando el login roto sin explicacion aparente.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core.apps.CoreConfig',

    'apps.catalog.apps.CatalogConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.orders.apps.OrdersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.orders.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# SQLite guarda UNICAMENTE usuarios y sesiones (el dominio vive en MongoDB
# detras de la API), pero en Vercel el sistema de archivos no persiste entre
# invocaciones de la funcion: un usuario registrado desaparecería en la
# siguiente peticion. Por eso, cuando existe DATABASE_URL (Postgres
# gestionado, inyectado por Vercel al conectar la integracion) se usa esa
# base; en desarrollo local, sin esa variable, se sigue usando SQLite.
if os.environ.get('DATABASE_URL'):
    _db_url = urllib.parse.urlparse(os.environ['DATABASE_URL'])
    # Neon (y la mayoria de Postgres gestionados) exigen SSL y lo indican con
    # ?sslmode=require en la URL. urlparse no mete la query en ningun otro
    # campo, asi que hay que reenviarla explicitamente como OPTIONS o
    # psycopg intentaria conectar sin SSL y Neon rechazaria la conexion.
    _db_options = dict(urllib.parse.parse_qsl(_db_url.query))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_url.path.lstrip('/'),
            'USER': _db_url.username,
            'PASSWORD': _db_url.password,
            'HOST': _db_url.hostname,
            'PORT': _db_url.port,
            'OPTIONS': _db_options,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Vercel ejecuta 'collectstatic' automaticamente durante el build y sirve lo
# recolectado aqui desde su CDN, pero solo si STATIC_ROOT esta definido.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Autenticacion ─────────────────────────────────────────
# SQLite guarda unicamente usuarios y sesiones; el dominio (productos,
# pedidos) vive en MongoDB detras de la API (ver apps/catalog/models.py).
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'catalog:product_list'
LOGOUT_REDIRECT_URL = 'catalog:product_list'

# ── API de TechGear (microservicio FastAPI) ───────────────
# El portal no tiene base de datos de dominio: productos y pedidos viven en la
# API. rstrip('/') evita URLs con doble barra al concatenar las rutas.
TECHGEAR_API_BASE_URL = os.environ.get(
    'TECHGEAR_API_BASE_URL', 'http://localhost:8001/api/v1'
).rstrip('/')

# Segundos de espera por peticion. Sin timeout, si la API se cuelga el portal
# se cuelga con ella.
TECHGEAR_API_TIMEOUT = int(os.environ.get('TECHGEAR_API_TIMEOUT', 10))

# Politica de reintentos del cliente HTTP. Los valores por defecto sirven para
# desarrollo local; contra la API desplegada en el plan gratuito de Render hay
# que ampliarlos, porque el servicio se duerme tras 15 minutos sin trafico y
# tarda cerca de un minuto en despertar (ver .env.example).
TECHGEAR_API_RETRIES = int(os.environ.get('TECHGEAR_API_RETRIES', 3))
TECHGEAR_API_BACKOFF = float(os.environ.get('TECHGEAR_API_BACKOFF', 0.3))
